### ISSUE TITLE
strict_en(de)code64 vs urlsafe_en(de)code64

### ISSUE THREAD

**Issue by azaceta** [rockandror/redsys-rails#6]
Estoy migrando la gema a ruby 1.8.7 para dar soporte a una aplicación 'legacy' mientras se actualiza a nuevas versiones.
Me he encontrado con la necesidad de codificar las funciones de Base64 strict_en/decode64 para cumplir con el RFC 4648, ya que no existen en 1.8.7
Al hacerlo y hacer pruebas he visto que las firmas de las notificaciones del TPV se corresponden a la codificación el urlsafe_encode64, que varía ligeramente de la del strict_encode64.
No encuentro documentación que lo corrobore. ¿Podéis confirmarlo? En caso afirmativo habría que cambiar las llamadas correspondientes.

**Comment by azaceta** [comment]
He _"verificado"_ que los datos que se envían al TPV solo los acepta si se utiliza `strict_encode64`, pero la firma que devuelve en la notificación solo se puede verificar con `urlsafe_encode64`. Esto no ocurre el 100% de las veces, únicamente cuando la firma incluye los caracteres `+` ó `/`, que es donde se produce la diferencia fundamental entre las dos funciones.
Se pueden ver las tablas de traducción en la página: [http://www.faqs.org/rfcs/rfc4648.html](url)
Apartado 4, tablas 1 y 2 respectivamente.
Estoy consultado con Redsys cuál es el formato adecuado (quizá pueda verse en las librerías php y similares)

**Comment by azaceta** [comment]
De acuerdo a lo que he visto en la librería PHP, veo que, efectivamente, la información que se envía va codificada en Base64 SIN url_safe, mientras que la que se recibe de la notificación viene codificada como url_safe.
Esto hay que tenerlo en cuenta en el notification controller, a la hora de verificar la firma y de recoger los parámetros. En alguno casos dará igual siempre que no contengan los caracteres `+` ni `/` pero en otros se producirán errores o datos incorrectos.

**Comment by guzmanthegood** [comment]
Hola @asierazaceta, gracias por las aportaciones y por el interés en sacar una versión retrocompatible. 

Entiendo que en el notification controller la instrucción Base64.strict_decode64 no "decodifica" correctamente cuando vienen caracteres raros, conviene utilizar la instrucción Base64.urlsafe_encode64 para evitar sustos.

Estoy dando mis primeros pasos en proyectos de participación abierta y me ha sorprendido gratamente el interés por esta gema. ¿Hay algo que pueda hacer para colaborar de forma activa o ayudarte en algo más? ¿La versión 'legacy' será otro repositorio o conviene que apliquemos los cambios en esta versión? ... como he dicho, estoy dando mis primeros pasos en proyectos colaborativos.

**Comment by azaceta** [comment]
Hola @guzmanweb , encantado, me ha venido de perlas encontrar tu gema, la creaste horas antes de que acabase desesperado de intentar integrarlo en el active merchant ;-)

Esto me contesta Redsys:

>  En respuesta a su correo y para poder solventar su incidencia le informamos que debe  codificar el valor + y / en hexadecimal, es decir, pasar el + como %2B y la / como %2F
> No obstante le aportamos una url donde puede revisar ejemplos de programación para tomarlas como referente a la programación que usted realiza.
> http://www.redsys.es/wps/portal/redsys/publica/areadeserviciosweb/descargaDeDocumentacionYEjecutables/

De lo que deduzco, junto con lo que vi en PHP que, efectivamente, la notificación hay que manejarla con urlsafe. Es más, las cadenas de hora y fecha de la transacción también hay que pasarlas por `URI.unscape` ya que vienen con caracteres válidos para URI.

A pesar de llevar muchos años por el mundo abierto, no he contribuido muy activamente con código en github antes, así que es nuevo para mi también. A ver si miro algún tutorial.
No se si lo mejor es mantener un fork retrocompatible, o dejarlo en una rama. Habrá que verlo.
Mi intención en cualquier caso es llevar las modificaciones a la versión última, ya que en cuanto podamos también migraremos la app legacy. Estudiemos la mejor manera de manejarlo.

Por cierto, aunque supongo que Redsys tiene uso solo en España, quizá convendría mantener código, comentarios y conversaciones aquí en Inglés para aumentar su difusión y uso. ¿qué opinas?

**Comment by guzmanthegood** [comment]
Hola @asierazaceta, 
me parecen perfectas todas las sugerencias. Ahora voy a estar un par de semanas centrado en otro proyecto que me urge bastante prisa y no puedo dedicarle el tiempo que me gustaría a este proyecto.

Sobre versiones, creo que el camino bueno es el que has tomado tu para que la gema sea retrocompatible, así que si te urge ahora mismo o lo tienes que integrar en algún proyecto, creo que lo mejor es que apliques los cambios en una rama nueva en un fork de este proyecto, yo más adelante puedo mergear los cambios y bajar la versión de ruby requerida y dejamos esta única versión 'legacy', ¿que opinas?

Sobre el idioma de comentarios y conversaciones, estuve apunto de hacerlo todo en inglés, pero como me muevo mejor en castellano y a priori Redsys es una plataforma española preferí, hacerlo en castellano y cuando tuviera una versión definitiva y funcional el traducirlo todo a inglés. En el código, a excepción de un par de comentarios explicativos, intento tirar siempre por el ingés.

Tengo otras ideas de mejora como dar la opción al usuario de añadir otro tipo de parámetros que la entidad financiera pueda solicitarle y que ahora no están contemplados y mejorar la documentación de como funciona el webhook de notificaciones, quizás incluso con algún gráfico. Incluso hablar con Redsys para dar a conocer este código y que le puedan dar mejor repercusión a sus clientes.

Un cordial saludo,

**Comment by azaceta** [comment]
This issue has been fixed, tested and merged
